### ISSUE TITLE
I cannot make solutions work

### ISSUE THREAD

**Issue by ArielUmansky** [mumuki/mumuki-minitest-runner#2]
I wasn't able to submit solutions successfully. 

Here's my setup: 

The expectations:
![image](https://user-images.githubusercontent.com/1649905/28896936-e6ca63d0-77b4-11e7-95d2-dc5b69ca3938.png)

The test (it's a placeholder..)
![image](https://user-images.githubusercontent.com/1649905/28896950-fd4d3650-77b4-11e7-9612-c954e4daff39.png)

The solution and the exercise description:
![image](https://user-images.githubusercontent.com/1649905/28897130-ae4c9478-77b5-11e7-94f9-d768eab6e77a.png)

The extra code (just in case):
![image](https://user-images.githubusercontent.com/1649905/28897005-2f26a634-77b5-11e7-92f0-828d0773308f.png)

The error that I'm getting when clicking on the submit button in the solutions tab:
![image](https://user-images.githubusercontent.com/1649905/28897032-569ff56c-77b5-11e7-8a11-c952dc9ebee1.png)

Stacktrace:
```
/usr/local/bundle/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load': solution.rb:24: syntax error, unexpected '{', expecting end-of-input (SyntaxError)
	from /usr/local/bundle/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
	from /usr/local/bundle/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
	from /usr/local/bundle/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
	from /usr/local/bundle/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
	from /usr/local/bundle/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
	from /usr/local/bundle/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
	from /usr/local/bundle/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /usr/local/bundle/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
	from /usr/local/bundle/bin/rspec:22:in `load'
	from /usr/local/bundle/bin/rspec:22:in `<main>'

```

Am I doing something wrong?

**Comment by flbulgarelli** [comment]
I think is not happening anymore.
